# -*- mode: ruby -*-
# vi: set ft=ruby :

# Notes:
#
#  1) vboxnet0 is assumed to be a host-only network @ address 172.28.128.1 (DHCP disabled)
#  2) Though not required, GOPATH is assumed to be the ../../../../../ directory
#  3) The directory on the VM Host will be /vagrant on the VM and be the path in GOPATH

Vagrant.configure(2) do |config|
  ['1', '2', '3', '4'].each do |idx|
    config.vm.define 'sdc'+idx do |node|
      node.vm.box = "centos-74-minimal-20171228"
      node.vm.box_url = "https://o.swiftstack.org/v1/AUTH_misc/vagrant_boxes/centos-74-minimal-20171228.box"
      node.vm.provider :virtualbox do |vb|
        vb.name = 'Samba DC '+idx
        vb.cpus = Integer(ENV['VAGRANT_CPUS'] || 1)
        vb.memory = Integer(ENV['VAGRANT_RAM'] || 1024)
      end
      node.vm.synced_folder "../../../../../", "/vagrant", type: "virtualbox"
      node.vm.network "private_network", ip: '172.28.128.1'+idx, :name => 'vboxnet0', :adapter => 2
      node.vm.provision "shell" do |s|
        s.path = "vagrant_provision.sh"
        s.args = ['sdc'+idx, '172.28.128.1'+idx, 'sdom'+idx]
      end
    end
  end
end
