# Note: I had to have ansible installed locally on my
# mac to get this to work.
N = 3
Vagrant::configure("2") do |config|
    (0..N-1).each do |machine_id|
        config.vm.box = "centos-74-minimal-20171228"
        config.vm.box_url = "https://o.swiftstack.org/v1/AUTH_misc/vagrant_boxes/centos-74-minimal-20171228.box"
        config.vm.synced_folder "../../../../../", "/vagrant", type: "virtualbox"
        config.vm.define "etcd#{machine_id}" do |machine|
            machine.vm.hostname = "etcd#{machine_id}"
            machine.vm.network "private_network", ip: "192.168.60.#{10+machine_id}", :name => "vboxnet0", :adapter => 2
            machine.vm.network "forwarded_port", guest: 15346, host: "#{25346+1+machine_id}"
            machine.vm.network "forwarded_port", guest: 15432, host: "#{25432+1+machine_id}"
            config.vm.provision "shell", env: {'DISTRO' => ENV['DISTRO']}, path: "vagrant_bootstrap.sh"
            if machine_id == N-1
                # Bootstrapping
                machine.vm.provision :ansible do |ansible|
                    ansible.limit = "all"
                    ansible.playbook = "setup.yaml"
                    ansible.version = "latest"
                end
            end
        end
    end
end
