# -*- mode: ruby -*-
# vi: set ft=ruby :

# Notes:
#
#   0) What follows assumes you have a running SAIO for ProxyFS VM sharing non-DHCP Host-only vboxnet0
#      (wherein your "host" is using 172.28.128.1 and the SAIO for ProxyFS VM is using 172.28.128.2)
#   1) "vagrant up" will likely have some problems connecting to Windows VM,
#      so just use VirtualBox Manager after initial provisioning
#   2) You may need to ^C out of the vagrant up command following provisioning
#   3) Subsequent restarts should just be done with VirtualBox Manager
#   4) To get to the console, launch VirtualBox Manager, select EdgeOnWindows10, and hit Show
#   5) You may be asked to Update OneDrive on first boot
#   6) Settings->Network&Internet->Ethernet->Change adapter options
#   7) Right-click to Properties on Ethernet2
#   8) Select Properties for Internet Protocol Version 4 (TCP/IPv4)
#   9) Select Use the following IP address and enter:
#        IP address:      172 .  28 . 128 . 3
#        Subnet mask:     255 . 255 . 255 . 0
#        Default gateway: 172 .  28 . 128 . 1 [as this is a Host-only network, you're not going anywhere else though]
#  10) OK/Close back out to Settings->Network&Internet->Ethernet and select Windows Firewall
#  11) Noting that Windows Firewall state is currently "On", select "Advanced settings" (on left)
#  12) At bottom of "Overview" section, select "Windows Firewall Properties"
#  13) For each of Domain Profile, Private Profile, and Public Profile tabs,
#      set Firewall state to "Off" and Apply
#  14) Open File Explorer
#  15) Right-click Network->Map network drive...
#  16) Enter \\172.28.128.2\proxyfs in Folder text box,
#      uncheck Reconnect at sign-in, and
#      check Connect using different credentials and hit Finish to map Drive Letter Z to your running ProxyFS VM
#  17) User name should be set to "\swift" (the leading backslash indicates a user not in a domain)
#      and a password of "swift" and hit "OK"
#  18) When you shutdown (probably after disconnecting Z:), you'll likely want to await the Windows Updates

Vagrant.configure(2) do |config|
  config.vm.box = "Microsoft/EdgeOnWindows10"
  config.vm.box_version = "1.0"
  config.vm.communicator = "winrm"
  config.vm.provider :virtualbox do |vb|
    vb.name = "EdgeOnWindows10"
    vb.cpus = Integer(ENV['VAGRANT_CPUS'] || 1)
    vb.memory = Integer(ENV['VAGRANT_RAM'] || 2048)
  end
  config.vm.network "private_network", ip: "172.28.128.3", :name => 'vboxnet0', :adapter => 2
end
