services:
- docker

git:
  submodules: false
  depth: false

notifications:
  slack:
    rooms:
      - secure: "qd9CCq5BJXolPXPvqXaeUcz1l1PchWO25efOhEyH0fE3SJfZVfAymUHLXblgd7GDD/lMJCJOngpBBiaDw/D2lBbTxHsZUliSKo5esg7Bxwm3MVNK3J5EKl63TPiLsbxrhAqcmrTf5DJHclJSnrZggv9RePZbZGNx+ByinC0DexZDps86kDK0KSlX2cox3wiuw4kRDyj37J+MY2o3OFk6riMqGBjnY0+ct3N5QN9NBkfWUQZ6T2pZ5X3+v12e6Q013wexfzOuRR/sJc4QXIfG6cJkR7JgE7CGxXVbqK1GGwHiKa1r0MIvOZQ5ggiCuHQq6ryowWLIk+0fu9y62HJ8tpCCNYz538XZAGDPxKQpxBGRtikgHwp3yfKZbQcHOJzFOLmtK9oYVV7WC6q6/dzYLpZLMm83F0Lz1blRoqtdvI6G/RjoT96p6GzptYcrdyLwh5/mJtuq49BAHeJQiGkN8XRybpz72dDYYfod9O4YW8L3xmjouIpMr9i/bw3PKC8PrynABo7ZCOLbBnBd/JpF45woTQhazTPqxWRVe0e6wFfFFKyG43jj4v2DVdHQ5xAsUPWdEsV2UfwwJFk71wPcjkXMC6I3ii19AUmhrM3CoWX4RKDR//P4h08kwfHm7/Jg+odCdoCc5qYhXYgRsR4HT2Vq3k8CtNZ/lPxEclPaMlQ="
    on_success: change
    on_failure: always
    on_pull_requests: true

before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive

script:
- docker run -e "COVERALLS_TOKEN=$COVERALLS_TOKEN" -e "TRAVIS_BRANCH=$TRAVIS_BRANCH" --cap-add SYS_ADMIN --device /dev/fuse -it -v `pwd`:/gopathroot/src/github.com/swiftstack/ProxyFS swiftstack/proxyfs_unit_tests
