# -*- mode: ruby -*-
# vi: set ft=ruby :

# Notes:
#
#  1) vboxnet0 is assumed to be a host-only network @ address 172.28.128.1 (DHCP disabled)
#  2) ProxyFS repo git clone'd to ProxyFS/src/github.com/swiftstack/
#  3) samba repo automatically staged in ProxyFS/src/github.com/swiftstack/ProxyFS/saio/
#  4) Swift repos et. al. git clone'd to ProxyFS/src/github.com/swiftstack/ProxyFS/saio/

Vagrant.configure(2) do |config|
  config.vm.box = "centos-74-minimal-20170913"
  config.vm.box_url = "https://o.swiftstack.org/v1/AUTH_misc/vagrant_boxes/centos-74-minimal-20170913.box"
  config.vm.provider :virtualbox do |vb|
    vb.name = "SAIO for ProxyFS"
    vb.cpus = Integer(ENV['VAGRANT_CPUS'] || 2)
    vb.memory = Integer(ENV['VAGRANT_RAM'] || 4096)
  end
  config.vm.synced_folder "../../../../../", "/vagrant", type: "virtualbox"
  config.vm.network "private_network", ip: "172.28.128.2", :name => 'vboxnet0', :adapter => 2
  config.vm.provision "shell", path: "vagrant_provision.sh"
end
