# -*- mode: ruby -*-
# vi: set ft=ruby :

# Notes:
#
#  1) vboxnet0 is assumed to be a host-only network @ address 172.28.128.1 (DHCP disabled)
#  2) Though not required, GOPATH is assumed to be the ../../../../../ directory
#  3) The directory on the VM Host will be /vagrant on the VM and be the path in GOPATH
#  4) ProxyFS repo git clone'd to $GOPATH/src/github.com/NVIDIA/
#  5) Swift repos et. al. git clone'd to $GOPATH/src/github.com/NVIDIA/proxyfs/saio/
#  6) ../Makefile will be ready to be executed after `cdpfs` inside the VM
#  7) As GOPATH is effectively shared between Host and VM, builds in the two environments
#     will collide in the contents of the $GOPATH/bin (only executables, not libraries)
#  8) With GOPATH now deprecated, much of the above concerns need to be modified (or ignored)

Vagrant.configure(2) do |config|
  config.vm.box = "centos-74-minimal-20180727"
  config.vm.box_url = "https://o.swiftstack.org/v1/AUTH_misc/vagrant_boxes/centos-74-minimal-20180727.box"
  config.vm.define "saiopfs" do |saiopfs|
  end
  config.vm.provider :virtualbox do |vb|
    vb.name = "SAIO for ProxyFS"
    vb.cpus = Integer(ENV['VAGRANT_CPUS'] || 2)
    vb.memory = Integer(ENV['VAGRANT_RAM'] || 6144)
    vb.customize ["modifyvm", :id, "--audio", "none"]
  end
  config.vm.synced_folder "../../../../../", "/vagrant", type: "virtualbox"
  config.vm.network "private_network", ip: "172.28.128.2", :name => 'vboxnet0', :adapter => 2
  config.vm.network "forwarded_port", guest: 15346, host: 15346
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8443, host: 8443
  config.vm.network "forwarded_port", guest: 32356, host: 32356
  config.vm.network "forwarded_port", guest: 9090, host: 9091
  config.vm.network "private_network", ip: "192.168.22.113", :name => 'vboxnet1', :adapter => 3
  config.vm.provision "shell", path: "vagrant_provision.sh"
end
