#!/usr/bin/env python

import json
import os
import subprocess
import sys


script_dir = os.path.abspath(os.path.dirname(__file__))
json_path = os.path.join(script_dir, "chef_files", "packages", "rhel_ss.json")

with open(json_path, "r") as json_file:
    versions_data = json.load(json_file)

everything_ok = True
for section, packages in versions_data.items():
    for package_info in packages:
        if len(package_info) == 1:
            continue
        package, pinned_version = package_info
        try:
            yum_versions = subprocess.check_output(
                "repoquery {} --queryformat '%{{vr}}'".format(package),
                shell=True, stderr=subprocess.STDOUT)
        except subprocess.CalledProcessError as e:
            print("! Error checking {}: {}".format(
                package, e.output.strip()))
            everything_ok = False
            continue
        yum_versions = yum_versions.strip().split("\n")
        if pinned_version not in yum_versions:
            print("{} not ok! pinned: {} | found in yum: {}".format(
                package, pinned_version, ", ".join(yum_versions)))
            everything_ok = False

if everything_ok:
    print("All pinned packages are installable")
else:
    print("\nFinished with errors")
    sys.exit(1)
