# Copyright (c) 2015-2021, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

gosubdir := github.com/NVIDIA/proxyfs/ihtml

generatedfiles := \
	bootstrap_dot_min_dot_css_.go \
	bootstrap_dot_min_dot_js_.go \
	jquery_dot_min_dot_js_.go \
	jquery_underline_3_dot_2_dot_1_dot_min_dot_js_.go \
	jsontree_dot_js_.go \
	open_iconic_bootstrap_dot_css_.go \
	open_iconic_dot_eot_.go \
	open_iconic_dot_otf_.go \
	open_iconic_dot_svg_.go \
	open_iconic_dot_ttf_.go \
	open_iconic_dot_woff_.go \
	popper_dot_min_dot_js_.go \
	styles_dot_css_.go \
	utils_dot_js_.go

include ../GoMakefile
