@startuml

[*] -> INIT
INIT --> OFFLINE
OFFLINE --> ONLINING : Start bringing VG ONLINE on a node
ONLINING --> ONLINE : VG finished coming ONLINE
ONLINE --> FAILED : For some reason the VG failed on a node
ONLINE --> OFFLINING : Start bringing the VG OFFLINE
OFFLINING --> OFFLINE : VG finished being brought OFFLINE
ONLINING --> FAILED : The VG failed to be brought ONLINE

@enduml
