# Copyright (c) 2015-2021, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

gosubdir := github.com/NVIDIA/proxyfs/make-static-content

generatedfiles := \
	make-static-content

include ../GoMakefile
