# -*- mode: ruby -*-
# vi: set ft=ruby :

# Notes:
#
#   1) vboxnet0 is assumed to be a host-only network @ address 172.28.128.1 (DHCP disabled)
#   2) Though not required, GOPATH is assumed to be the ../../../../../ directory
#   3) The directory on the VM Host will be /vagrant on the VM and be the path in GOPATH
#   4) ProxyFS repo git clone'd to $GOPATH/src/github.com/NVIDIA/
#   5) samba repo automatically staged in $GOPATH/src/github.com/NVIDIA/proxyfs/saio/
#   6) Swift repos et. al. git clone'd to $GOPATH/src/github.com/NVIDIA/proxyfs/saio/
#   7) ../Makefile will be ready to be executed after `cdpfs` inside the VM
#   8) As GOPATH is effectively shared between Host and VM, builds in the two environments
#      will collide in the contents of the $GOPATH/bin (only executables, not libraries)
#   9) As of now, only ProxyFS is supported (no Samba, no ramswift), so, at the most,
#      users shoult only do `make version fmt pre-generate generate install`
#  10) Only the following tools in bin/ are currently supported:
#        provision_middleware
#        start_proxyfs_and_swift
#        start_swift_only
#        unmount_and_stop_pfs
#  11) bin/start_proxyfs_and_swift requires an argument of either 1, 2, or 3
#  12) home/swift/bin/resetswift   requires an argument of either 1, 2, or 3

Vagrant.configure(2) do |config|
  config.vm.define "sait1" do |sconfig|
    sconfig.vm.box = "centos-74-minimal-20180727"
    sconfig.vm.box_url = "https://o.swiftstack.org/v1/AUTH_misc/vagrant_boxes/centos-74-minimal-20180727.box"
    sconfig.vm.define "sait1pfs" do |sait1pfs|
    end
    sconfig.vm.provider :virtualbox do |vb|
      vb.name = "SAIT 1 for ProxyFS"
      vb.cpus = Integer(ENV['VAGRANT_CPUS'] || 1)
      vb.memory = Integer(ENV['VAGRANT_RAM'] || 2048)
      vb.customize ["modifyvm", :id, "--audio", "none"]
    end
    sconfig.vm.synced_folder "../../../../../", "/vagrant", type: "virtualbox"
    sconfig.vm.network "private_network", ip: "172.28.128.3", :name => 'vboxnet0', :adapter => 2
    sconfig.vm.network "forwarded_port", guest: 15346, host: 15347
    sconfig.vm.network "forwarded_port", guest: 9090, host: 9092
    sconfig.vm.network "private_network", ip: "192.168.22.114", :name => 'vboxnet1', :adapter => 3
    sconfig.vm.provision "shell", path: "vagrant_provision.sh", args: "1"
  end

  config.vm.define "sait2" do |sconfig|
    sconfig.vm.box = "centos-74-minimal-20180727"
    sconfig.vm.box_url = "https://o.swiftstack.org/v1/AUTH_misc/vagrant_boxes/centos-74-minimal-20180727.box"
    sconfig.vm.define "sait2pfs" do |sait2pfs|
    end
    sconfig.vm.provider :virtualbox do |vb|
      vb.name = "SAIT 2 for ProxyFS"
      vb.cpus = Integer(ENV['VAGRANT_CPUS'] || 1)
      vb.memory = Integer(ENV['VAGRANT_RAM'] || 2048)
      vb.customize ["modifyvm", :id, "--audio", "none"]
    end
    sconfig.vm.synced_folder "../../../../../", "/vagrant", type: "virtualbox"
    sconfig.vm.network "private_network", ip: "172.28.128.4", :name => 'vboxnet0', :adapter => 2
    sconfig.vm.network "forwarded_port", guest: 15346, host: 15348
    sconfig.vm.network "forwarded_port", guest: 9090, host: 9093
    sconfig.vm.network "private_network", ip: "192.168.22.115", :name => 'vboxnet1', :adapter => 3
    sconfig.vm.provision "shell", path: "vagrant_provision.sh", args: "2"
  end

  config.vm.define "sait3" do |sconfig|
    sconfig.vm.box = "centos-74-minimal-20180727"
    sconfig.vm.box_url = "https://o.swiftstack.org/v1/AUTH_misc/vagrant_boxes/centos-74-minimal-20180727.box"
    sconfig.vm.define "sait1pfs" do |sait3pfs|
    end
    sconfig.vm.provider :virtualbox do |vb|
      vb.name = "SAIT 3 for ProxyFS"
      vb.cpus = Integer(ENV['VAGRANT_CPUS'] || 1)
      vb.memory = Integer(ENV['VAGRANT_RAM'] || 2048)
      vb.customize ["modifyvm", :id, "--audio", "none"]
    end
    sconfig.vm.synced_folder "../../../../../", "/vagrant", type: "virtualbox"
    sconfig.vm.network "private_network", ip: "172.28.128.5", :name => 'vboxnet0', :adapter => 2
    sconfig.vm.network "forwarded_port", guest: 15346, host: 15349
    sconfig.vm.network "forwarded_port", guest: 9090, host: 9094
    sconfig.vm.network "private_network", ip: "192.168.22.116", :name => 'vboxnet1', :adapter => 3
    sconfig.vm.provision "shell", path: "vagrant_provision.sh", args: "3"
  end
end
