gosubdir := github.com/swiftstack/ProxyFS/httpserver

generatedfiles := \
	bootstrap_dot_min_dot_css.go \
	bootstrap_dot_min_dot_js.go \
	jsontree_dot_js.go \
	jquery_underline_3_dot_2_dot_1_dot_min_dot_js.go \
	open_iconic_bootstrap_dot_css.go \
	open_iconic_dot_eot.go \
	open_iconic_dot_otf.go \
	open_iconic_dot_svg.go \
	open_iconic_dot_ttf.go \
	open_iconic_dot_woff.go \
	popper_dot_min_dot_js.go \
	proxyfs_version.go \
	styles_dot_css.go

include ../GoMakefile
